### ISSUE TITLE
Missing Package ID in XML

### ISSUE THREAD

**Issue by djmerrill** [JITx-Inc/darpa-idea#1]
Missing package name in XML ESIR.

Should look like this I think: <PCBPACKAGE name="RESC1005X35">   

<img width="582" alt="Screen Shot 2019-07-18 at 6 15 26 PM" src="https://user-images.githubusercontent.com/9127315/61495804-ec738080-a96e-11e9-9d2f-f14f4c1200ac.png">
<img width="506" alt="Screen Shot 2019-07-18 at 6 10 15 PM" src="https://user-images.githubusercontent.com/9127315/61495808-f0070780-a96e-11e9-9a51-f496c81bb33f.png">

**Comment by d-haldane** [comment]
Fixed! New example a-resistor.xml is in docs/xml-examples
